name: dart_openai_plus
description: An open-source package that allows developers to easily integrate the power of OpenAI's state-of-the-art AI models into their Dart/Flutter applications.
version: 1.0.0
homepage: https://github.com/ChunhThanhDe/openai.dart
repository: https://github.com/ChunhThanhDe/openai.dart
documentation: https://github.com/ChunhThanhDe/openai.dart/blob/main/README.md
issue_tracker: https://github.com/ChunhThanhDe/openai.dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.3.0
  meta: ^1.16.0
  collection: ^1.19.1
  fetch_client: ^1.1.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
