name: Release Workflow.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checking commit message
        run: |
          if grep -iq "release" "$GITHUB_EVENT_PATH"; then
            echo "This commit contains the word 'release'. Creating a release..."
          else
            echo "This commit does not contain the word 'release'. Exiting workflow."
            exit 78
          fi

      - name: Extracting Version Number Of The Current Release
        run: |
          VERSION=$(grep -oP "version:\s*\K.*" pubspec.yaml)
          echo "VERSION: V$VERSION detected"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Creating New Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: false
